export interface SportDrill {
  name: string;
  description: string;
}

export interface SportData {
  name: string;
  emoji: string;
  about: string;
  origin: string;
  sportsSpecificOrigin: string;
  activities: string[];
  exercises: string[];
  drills: SportDrill[];
  practiceSuggestions: string[];
  trainingActivities: string[];
  facilities: string[];
  equipment: string[];
  usesFunctions: string;
  properUseSafety: string[];
  learningInfo: string;
}

export const SPORTS_DATA: Record<string, SportData> = {
  Swimming: {
    name: "Swimming",
    emoji: "🏊",
    about: "Swimming is an aquatic sport involving movement through water using different strokes.",
    origin: "Swimming is one of the oldest forms of physical activity. People have practiced swimming since ancient times for survival, recreation, and physical development. Modern competitive swimming developed into an organized sport during the 19th century and later became an international competitive sport.",
    sportsSpecificOrigin: "Swimming has ancient roots, while modern competitive swimming developed into an organized sport particularly in the 19th century. World Aquatics records organized national championships in England in the 19th century and traces the development of the modern competitive discipline.",
    activities: ["Freestyle", "Breaststroke", "Backstroke", "Butterfly", "Starts", "Turns", "Water-safety activities"],
    exercises: ["Kick exercises", "Core exercises", "Flexibility exercises", "Body-position exercises"],
    drills: [
      { name: "Kicking Drill", description: "Hold a kickboard and kick continuously." },
      { name: "Breathing Drill", description: "Practice controlled breathing while swimming." },
      { name: "Stroke Drill", description: "Practice proper arm and leg movement for a selected stroke." },
    ],
    practiceSuggestions: ["Practice proper body position.", "Practice breathing technique.", "Focus on smooth and controlled strokes.", "Follow pool safety rules."],
    trainingActivities: ["Warm-up", "Technique practice", "Endurance swimming", "Cool-down"],
    facilities: ["Swimming Pool — the main facility where swimming activities and competitions are conducted.", "Swimming Lanes — divided areas that help swimmers maintain their assigned swimming space.", "Starting Area — the area where swimmers begin a race.", "Pool Deck — the area surrounding the swimming pool used for preparation and movement."],
    equipment: ["Goggles — protect the eyes and help swimmers see clearly underwater.", "Swim Cap — helps keep hair away from the face and reduces resistance in the water.", "Kickboard — supports the upper body while practicing kicking.", "Pull Buoy — helps support the legs while practicing arm strokes.", "Fins — help improve kicking technique and leg strength.", "Stopwatch — used to record swimming time."],
    usesFunctions: "Swimming equipment is used to support training, improve technique, measure performance, and provide safety during practice.",
    properUseSafety: ["Follow the instructions of the teacher or coach.", "Warm up before entering the pool.", "Walk instead of running around the pool.", "Use swimming equipment correctly.", "Do not swim alone.", "Follow pool rules and safety signs."],
    learningInfo: "Students can learn about swimming strokes, starts, turns, breathing techniques, basic swimming rules, water safety, and competition procedures.",
  },
  Athletics: {
    name: "Athletics",
    emoji: "🏃",
    about: "Athletics includes running, jumping, and throwing events.",
    origin: "Athletics has roots in ancient physical competitions involving running, jumping, and throwing. Over time, these activities developed into organized track-and-field events and became part of international sporting competitions.",
    sportsSpecificOrigin: "Athletics has roots in ancient competitions and has developed over thousands of years. World Athletics describes athletics as a sport founded in antiquity and traces organized developments through the modern era.",
    activities: ["Sprinting", "Distance running", "Relay", "Long jump", "High jump", "Throwing events"],
    exercises: ["Squats", "Lunges", "Calf raises", "Core exercises", "Dynamic stretching"],
    drills: [
      { name: "Sprint Start Drill", description: "Practice starting position and acceleration." },
      { name: "Relay Drill", description: "Practice running and baton exchange." },
      { name: "Jump Drill", description: "Practice take-off and landing technique." },
    ],
    practiceSuggestions: ["Maintain proper running form.", "Practice acceleration.", "Practice safe landing.", "Use throwing areas only under supervision."],
    trainingActivities: ["Warm-up", "Speed training", "Strength training", "Endurance training", "Cool-down"],
    facilities: ["Running Track — used for running and relay events.", "Long Jump Area — used for long-jump competitions.", "High Jump Area — used for high-jump events.", "Throwing Area — used for events such as shot put and discus."],
    equipment: ["Starting Blocks — help sprinters begin races effectively.", "Hurdles — used in hurdle races.", "Relay Baton — passed between team members during relay races.", "Stopwatch — measures running time.", "Measuring Tape — measures jumping and throwing distances.", "Shot Put/Discus — used in throwing events."],
    usesFunctions: "Athletics facilities and equipment help athletes perform different running, jumping, and throwing events safely and accurately.",
    properUseSafety: ["Wear appropriate sports shoes.", "Warm up before training.", "Use throwing areas only when they are clear.", "Follow the coach's instructions.", "Keep proper distance from throwing activities.", "Use equipment only for its intended purpose."],
    learningInfo: "Students can learn about track and field events, starting techniques, running techniques, jumping techniques, throwing techniques, event rules, and basic competition procedures.",
  },
  Basketball: {
    name: "Basketball",
    emoji: "🏀",
    about: "Basketball is a team sport in which players attempt to score by putting the ball through the opponent's basket.",
    origin: "Basketball was invented by James Naismith in 1891 in Springfield, Massachusetts, USA. It developed from a simple indoor activity into an internationally played team sport.",
    sportsSpecificOrigin: "Basketball was created by James Naismith in Springfield, Massachusetts, in 1891. The first game was played on December 21, 1891.",
    activities: ["Dribbling", "Passing", "Shooting", "Lay-up", "Rebounding", "Defensive movement"],
    exercises: ["Squats", "Lunges", "Jumping exercises", "Core exercises", "Calf raises"],
    drills: [
      { name: "Dribbling Drill", description: "Control the ball while moving." },
      { name: "Passing Drill", description: "Pass accurately to a teammate." },
      { name: "Shooting Drill", description: "Practice shooting with proper form." },
      { name: "Defensive Footwork Drill", description: "Move sideways while maintaining defensive position." },
    ],
    practiceSuggestions: ["Practice ball control.", "Practice shooting from different positions.", "Practice passing accuracy.", "Keep proper defensive stance."],
    trainingActivities: ["Dynamic warm-up", "Agility training", "Speed training", "Endurance training", "Cool-down"],
    facilities: ["Basketball Court — the main playing area.", "Basketball Ring — the target through which players shoot the ball.", "Backboard — supports the ring and provides a surface for bank shots.", "Free-Throw Line — the line from which free throws are taken.", "Three-Point Line — marks the area for three-point shots."],
    equipment: ["Basketball — the main ball used in the game.", "Basketball Ring — the scoring target.", "Backboard — supports the ring.", "Cones — used for training drills.", "Agility Ladder — used for footwork exercises.", "Whistle — used by officials or coaches to signal actions."],
    usesFunctions: "Basketball equipment supports playing, training, skill development, officiating, and physical conditioning.",
    properUseSafety: ["Wear appropriate basketball shoes.", "Warm up before playing.", "Use proper passing and shooting techniques.", "Do not hang on the basketball ring.", "Keep the court free from unnecessary objects.", "Follow the rules and instructions of the teacher or coach."],
    learningInfo: "Students can learn about dribbling, passing, shooting, rebounding, defense, player positions, basic rules, violations, scoring, and game procedures.",
  },
  Badminton: {
    name: "Badminton",
    emoji: "🏸",
    about: "Badminton is a racket sport in which players hit a shuttlecock across a net.",
    origin: "Badminton developed from earlier shuttlecock games played in different parts of the world. The modern form of badminton developed through organized play and became an international racket sport.",
    sportsSpecificOrigin: "Badminton has roots in older shuttlecock games from Europe and Asia. The modern form developed gradually, with important developments in England and India; the BWF describes the development of the modern game and notes the role of the Indian game known as poona.",
    activities: ["Serving", "Forehand", "Backhand", "Clear", "Drop shot", "Smash", "Net play"],
    exercises: ["Lunges", "Squats", "Core exercises", "Footwork exercises"],
    drills: [
      { name: "Serving Drill", description: "Practice hitting the shuttle accurately into the service area." },
      { name: "Forehand Drill", description: "Practice controlled forehand strokes." },
      { name: "Footwork Drill", description: "Move quickly to different areas of the court." },
    ],
    practiceSuggestions: ["Practice racket control.", "Maintain proper footwork.", "Focus on accuracy before power.", "Practice both forehand and backhand."],
    trainingActivities: ["Warm-up", "Footwork training", "Agility training", "Reaction-time practice", "Cool-down"],
    facilities: ["Badminton Court — the playing area for singles and doubles matches.", "Net — divides the two sides of the court.", "Posts — support the net.", "Service Areas — designated areas where serves must land."],
    equipment: ["Racket — used to hit the shuttlecock.", "Shuttlecock — the object hit across the net.", "Net — separates the players or teams.", "Court Markings — identify the boundaries and service areas.", "Sports Shoes — provide support and traction during movement."],
    usesFunctions: "Badminton equipment allows players to perform serves, strokes, movements, and other game skills safely and effectively.",
    properUseSafety: ["Hold the racket properly.", "Use the racket only for playing.", "Wear appropriate court shoes.", "Keep enough space between players.", "Do not swing the racket near another person.", "Follow the coach's instructions."],
    learningInfo: "Students can learn about serving, clear shots, drop shots, smashes, net shots, footwork, singles and doubles play, scoring, and basic rules.",
  },
  Chess: {
    name: "Chess",
    emoji: "♟️",
    about: "Chess is a two-player strategy game that requires planning, tactical thinking, concentration, and decision-making.",
    origin: "Chess originated from an ancient Indian strategy game commonly associated with chaturanga. It spread to Persia and later to other parts of the world, eventually developing into the modern game of chess.",
    sportsSpecificOrigin: "Chess originated in India, developing from an early form known as chaturanga. It later spread to Persia and the wider world.",
    activities: ["Opening practice", "Tactical problems", "Strategy", "Endgame practice", "Game analysis"],
    exercises: ["Tactical puzzles", "Calculation exercises", "Board-visualization exercises"],
    drills: [
      { name: "Checkmate Drill", description: "Find the correct move to checkmate." },
      { name: "Tactical Drill", description: "Solve a short tactical position." },
      { name: "Opening Drill", description: "Practice common opening moves." },
    ],
    practiceSuggestions: ["Analyze previous games.", "Practice tactical positions.", "Learn basic opening principles.", "Review mistakes after each game."],
    trainingActivities: ["Game analysis", "Strategy practice", "Concentration practice", "Time-management practice"],
    facilities: ["Chess Playing Area — a quiet area where students can play and study chess.", "Chess Table — provides a stable surface for the board.", "Tournament Area — a designated space for organized competitions."],
    equipment: ["Chessboard — the playing board containing 64 squares.", "Chess Pieces — the king, queen, rooks, bishops, knights, and pawns.", "Chess Clock — used to control the time of each player's game.", "Notation Sheet — used to record moves during a game."],
    usesFunctions: "Chess equipment supports playing, analyzing, recording, and organizing chess games and competitions.",
    properUseSafety: ["Handle the chess pieces carefully.", "Keep the playing area clean and organized.", "Use the chess clock properly.", "Avoid disturbing other players during games.", "Observe fair-play practices."],
    learningInfo: "Students can learn about chess pieces, movement rules, openings, tactics, strategy, check, checkmate, endgame principles, notation, and time control.",
  },
  Arnis: {
    name: "Arnis",
    emoji: "🪃",
    about: "Arnis is a Filipino martial art and sport involving striking, blocking, thrusting, parrying, footwork, and related defensive techniques.",
    origin: "Arnis is a traditional Filipino martial art and sport that emphasizes weapon-based and empty-hand techniques. It is recognized as the national martial art and sport of the Philippines under Republic Act No. 9850.",
    sportsSpecificOrigin: "Arnis is an indigenous Filipino martial art and sport. Republic Act No. 9850 officially declares Arnis the Philippine national martial art and sport.",
    activities: ["Basic strikes", "Blocking", "Footwork", "Defensive movement", "Offensive movement", "Sinawali"],
    exercises: ["Squats", "Lunges", "Core exercises", "Coordination exercises"],
    drills: [
      { name: "Basic Striking Drill", description: "Practice controlled strikes using proper technique." },
      { name: "Blocking Drill", description: "Practice blocking incoming strikes." },
      { name: "Footwork Drill", description: "Practice forward, backward, and side movement." },
    ],
    practiceSuggestions: ["Maintain proper stance.", "Practice controlled movements.", "Use protective equipment.", "Practice under teacher/coach supervision."],
    trainingActivities: ["Warm-up", "Coordination training", "Agility training", "Reaction-time practice", "Cool-down"],
    facilities: ["Training Area — a clear area used for Arnis practice.", "Martial Arts Mat — provides a suitable surface for training.", "Practice Area — a designated space for controlled drills and exercises."],
    equipment: ["Arnis Sticks — used for controlled striking and blocking practice.", "Headgear — protects the head during appropriate training or competition.", "Protective Gloves — help protect the hands.", "Body Protector — provides protection during controlled contact.", "Training Targets — used for practicing strikes."],
    usesFunctions: "Arnis equipment supports the practice of striking, blocking, footwork, coordination, and controlled martial arts techniques.",
    properUseSafety: ["Use protective equipment when required.", "Practice only under qualified supervision.", "Maintain a safe distance from others.", "Never strike another person outside controlled practice.", "Check equipment before use.", "Follow proper technique and safety instructions."],
    learningInfo: "Students can learn about basic strikes, blocks, footwork, defensive techniques, offensive techniques, combinations, terminology, rules, and safety practices.",
  },
  Football: {
    name: "Football",
    emoji: "⚽",
    about: "Football is a team sport in which players attempt to score by getting the ball into the opponent's goal.",
    origin: "Modern association football developed in England, where standardized Laws of the Game were established in the 19th century. It later became one of the most widely played team sports internationally.",
    sportsSpecificOrigin: "The modern universal Laws of association football were first drawn up in England in 1863.",
    activities: ["Passing", "Receiving", "Dribbling", "Ball control", "Shooting", "Defending", "Attacking"],
    exercises: ["Squats", "Lunges", "Core exercises", "Sprinting", "Calf exercises"],
    drills: [
      { name: "Dribbling Drill", description: "Control the ball while moving." },
      { name: "Passing Drill", description: "Pass accurately to a teammate." },
      { name: "Shooting Drill", description: "Practice shooting toward the goal." },
    ],
    practiceSuggestions: ["Practice ball control.", "Keep your head up while dribbling.", "Practice accurate passing.", "Use proper protective equipment."],
    trainingActivities: ["Warm-up", "Speed training", "Agility training", "Endurance training", "Cool-down"],
    facilities: ["Football Field/Pitch — the main playing area.", "Goal Area — the area around the goal.", "Penalty Area — the designated area where specific rules apply.", "Goals — the targets used for scoring."],
    equipment: ["Football — the main ball used in the game.", "Goalposts and Net — form the scoring target.", "Cones — used for training drills.", "Shin Guards — protect the lower legs.", "Goalkeeper Gloves — protect the goalkeeper's hands and improve grip.", "Football Shoes — provide traction on the playing surface."],
    usesFunctions: "Football facilities and equipment support playing, training, skill development, and player safety.",
    properUseSafety: ["Wear appropriate football shoes and shin guards.", "Warm up before playing.", "Use equipment correctly.", "Avoid dangerous tackles.", "Follow the Laws of the Game and coach's instructions.", "Keep the playing area safe and clear."],
    learningInfo: "Students can learn about passing, receiving, dribbling, shooting, defending, attacking, player positions, scoring, fouls, and basic game rules.",
  },
  Taekwondo: {
    name: "Taekwondo",
    emoji: "🥋",
    about: "Taekwondo is a Korean martial art and combat sport emphasizing kicking, footwork, balance, speed, and controlled techniques.",
    origin: "Taekwondo is a Korean martial art and combat sport known particularly for its kicking techniques, movement, balance, and discipline. It developed in Korea and later became an internationally practiced sport.",
    sportsSpecificOrigin: "World Taekwondo describes Taekwondo as a Korean martial art whose origins can be traced back thousands of years and which later developed into an international sport.",
    activities: ["Stance", "Footwork", "Kicking", "Punching", "Blocking", "Combinations"],
    exercises: ["Squats", "Lunges", "Flexibility exercises", "Balance exercises", "Core exercises"],
    drills: [
      { name: "Front-Kick Drill", description: "Practice lifting the knee and extending the foot forward with control." },
      { name: "Blocking Drill", description: "Practice correct blocking movements." },
      { name: "Footwork Drill", description: "Practice moving while maintaining proper stance." },
    ],
    practiceSuggestions: ["Maintain proper stance.", "Focus on technique before speed.", "Stretch safely.", "Use protective equipment."],
    trainingActivities: ["Warm-up", "Flexibility training", "Balance training", "Reaction-time training", "Cool-down"],
    facilities: ["Training Area — a clear space for Taekwondo practice.", "Martial Arts Mat — provides a suitable surface for training.", "Competition Area — a designated area for formal competition."],
    equipment: ["Dobok — the traditional uniform worn during training and competition.", "Head Guard — protects the head.", "Chest Protector — protects the torso.", "Forearm and Shin Guards — provide protection during training and competition.", "Kicking Pads — used for practicing kicks."],
    usesFunctions: "Taekwondo facilities and equipment support training, skill development, controlled practice, and participant safety.",
    properUseSafety: ["Wear the required protective equipment.", "Practice under qualified supervision.", "Use controlled movements during drills.", "Maintain proper distance.", "Follow competition and training rules.", "Do not perform uncontrolled contact."],
    learningInfo: "Students can learn about basic stances, footwork, kicks, blocks, punches, combinations, scoring, terminology, discipline, and safety.",
  },
  Volleyball: {
    name: "Volleyball",
    emoji: "🏐",
    about: "Volleyball is a team sport in which players send a ball over a net and try to make it land on the opponent's court.",
    origin: "Volleyball was created by William G. Morgan in 1895 at the YMCA in Holyoke, Massachusetts, USA. It was originally called Mintonette and later developed into the modern international sport of volleyball.",
    sportsSpecificOrigin: "Volleyball was invented by William G. Morgan in 1895 at the YMCA in Holyoke, Massachusetts. It was originally called Mintonette.",
    activities: ["Serving", "Passing", "Setting", "Spiking", "Blocking", "Digging"],
    exercises: ["Squats", "Lunges", "Jumping exercises", "Core exercises"],
    drills: [
      { name: "Serving Drill", description: "Toss the ball and serve it over the net with proper technique." },
      { name: "Passing Drill", description: "Use the forearms to direct the ball to a target." },
      { name: "Spiking Drill", description: "Practice approach, jump, and controlled hitting of the ball. The student does not need to hold another object while spiking; the volleyball itself is the ball being hit." },
    ],
    practiceSuggestions: ["Practice accurate serving.", "Maintain proper passing position.", "Practice the approach and jump before focusing on power.", "Communicate with teammates."],
    trainingActivities: ["Dynamic warm-up", "Agility training", "Jump training", "Reaction-time training", "Cool-down"],
    facilities: ["Volleyball Court — the main playing area.", "Net — divides the two teams.", "Center Line — separates the playing areas.", "Attack Line — marks the front and back zones of the court."],
    equipment: ["Volleyball — the main ball used in the game.", "Net — separates the two teams.", "Posts — support the net.", "Antennas — help identify the crossing space above the net.", "Knee Pads — help protect the knees.", "Cones — used for training drills."],
    usesFunctions: "Volleyball facilities and equipment support playing, training, movement, skill development, and player safety.",
    properUseSafety: ["Wear appropriate court shoes.", "Warm up before playing.", "Use proper passing and jumping techniques.", "Do not pull or hang on the net.", "Keep the court clear.", "Follow the teacher or coach's instructions."],
    learningInfo: "Students can learn about serving, passing, setting, spiking, blocking, digging, player positions, rotation, scoring, and basic volleyball rules.",
  },
  "Sepak Takraw": {
    name: "Sepak Takraw",
    emoji: "🦵",
    about: "Sepak Takraw is a Southeast Asian net sport in which players use their feet and other permitted body parts to control and send a ball over a net.",
    origin: "Sepak Takraw developed from traditional ball games in Southeast Asia. Earlier forms were commonly associated with sepak raga, in which players kept a ball in the air using their feet and other parts of the body. The modern sport developed into a competitive net game.",
    sportsSpecificOrigin: "The sport developed from traditional Southeast Asian games, including sepak raga, in which players kept a ball in the air using their feet, knees, head, and chest.",
    activities: ["Kicking", "Ball control", "Passing", "Serving", "Receiving", "Heading", "Footwork"],
    exercises: ["Squats", "Lunges", "Balance exercises", "Flexibility exercises", "Core exercises"],
    drills: [
      { name: "Kicking Drill", description: "Use the foot to keep the ball in the air." },
      { name: "Serving Drill", description: "Practice sending the ball over the net." },
      { name: "Receiving Drill", description: "Control the ball using the foot, knee, chest, or head." },
    ],
    practiceSuggestions: ["Practice ball control first.", "Maintain balance while kicking.", "Practice receiving from different directions."],
    trainingActivities: ["Warm-up", "Coordination training", "Agility training", "Balance training", "Cool-down"],
    facilities: ["Sepak Takraw Court — the main playing area.", "Net — separates the two teams.", "Service Circle — used during service.", "Playing Boundary — marks the limits of the court."],
    equipment: ["Takraw Ball — the main ball used in the sport.", "Net — separates the teams.", "Posts — support the net.", "Cones — used for training.", "Sports Shoes — provide support and traction."],
    usesFunctions: "The facilities and equipment support kicking, serving, receiving, ball control, and other technical skills.",
    properUseSafety: ["Warm up before playing.", "Wear appropriate sports shoes.", "Use the ball and net correctly.", "Maintain enough space during kicking drills.", "Follow the coach's instructions.", "Avoid dangerous movements near other players."],
    learningInfo: "Students can learn about serving, kicking, receiving, setting, ball control, heading, player roles, scoring, and basic rules.",
  },
  "Wushu Sanda": {
    name: "Wushu Sanda",
    emoji: "🥊",
    about: "Wushu Sanda is a modern unarmed combat sport developed from traditional wushu techniques. It includes punches, kicks, throws, wrestling, and defensive techniques.",
    origin: "Wushu Sanda is a modern combat sport developed from Chinese martial arts. It combines controlled punching, kicking, throwing, wrestling techniques, and defensive movements.",
    sportsSpecificOrigin: "Sanda developed from Chinese wushu/martial-arts training into a modern competitive combat sport.",
    activities: ["Stance", "Footwork", "Punching", "Kicking", "Defensive movement", "Controlled sparring"],
    exercises: ["Squats", "Lunges", "Core exercises", "Flexibility exercises", "Balance exercises"],
    drills: [
      { name: "Punching Drill", description: "Practice controlled straight punches with proper stance." },
      { name: "Kicking Drill", description: "Practice controlled kicks with proper balance." },
      { name: "Pad Drill", description: "Practice techniques using a coach-held pad." },
    ],
    practiceSuggestions: ["Use protective equipment.", "Practice techniques under qualified supervision.", "Focus on control and correct form.", "Do not practice full-contact techniques without proper supervision."],
    trainingActivities: ["Warm-up", "Footwork", "Pad work", "Conditioning", "Cool-down"],
    facilities: ["Training Area — a clear space for martial arts training.", "Martial Arts Mat/Platform — provides a suitable surface for practice and competition.", "Training Zone — used for technical drills and controlled practice."],
    equipment: ["Sanda Gloves — protect the hands during training and competition.", "Headgear — provides head protection when required.", "Chest Protector — helps protect the torso.", "Shin Guards — help protect the lower legs.", "Focus Mitts/Training Pads — used for controlled striking practice."],
    usesFunctions: "Sanda equipment supports technical training, controlled striking, defensive practice, and participant safety.",
    properUseSafety: ["Wear appropriate protective equipment.", "Train only under qualified supervision.", "Use controlled techniques during drills.", "Do not engage in unsupervised full-contact practice.", "Check protective equipment before use.", "Follow the rules and instructions of the coach."],
    learningInfo: "Students can learn about stance, footwork, punches, kicks, defensive techniques, throws, combinations, scoring, rules, and safety practices.",
  },
  Wrestling: {
    name: "Wrestling",
    emoji: "🤼",
    about: "Wrestling is a combat sport involving grappling, takedowns, holds, escapes, and control of an opponent.",
    origin: "Wrestling is one of the oldest forms of combat sport. Evidence of wrestling can be found in ancient civilizations, including ancient Egypt, Sumer, and Greece. It later developed into organized modern wrestling styles and competitions.",
    sportsSpecificOrigin: "Wrestling has extremely ancient roots. United World Wrestling traces early evidence to civilizations including Sumer and ancient Egypt and notes its importance in ancient Greek athletics.",
    activities: ["Wrestling stance", "Movement", "Takedowns", "Holds", "Escapes", "Defensive techniques"],
    exercises: ["Squats", "Lunges", "Bridges", "Core exercises", "Strength exercises"],
    drills: [
      { name: "Stance and Movement Drill", description: "Maintain a low stance while moving around an opponent." },
      { name: "Takedown Drill", description: "Practice controlled takedown technique under supervision." },
      { name: "Escape Drill", description: "Practice safe movement to escape a controlled position." },
    ],
    practiceSuggestions: ["Maintain proper body position.", "Practice with a qualified coach.", "Use a proper wrestling mat.", "Follow safety rules."],
    trainingActivities: ["Warm-up", "Strength training", "Balance training", "Conditioning", "Cool-down"],
    facilities: ["Wrestling Mat — the main surface used for wrestling.", "Training Area — a designated space for learning techniques.", "Practice Area — used for controlled drills and physical preparation."],
    equipment: ["Wrestling Mat — provides a suitable and safer surface for wrestling.", "Singlet — the traditional competition uniform.", "Wrestling Shoes — provide grip and support.", "Headgear — helps protect the ears during practice and competition.", "Training Dummy — used to practice techniques without a live partner."],
    usesFunctions: "Wrestling facilities and equipment support grappling practice, takedowns, escapes, physical conditioning, and safety.",
    properUseSafety: ["Keep the wrestling mat clean.", "Warm up before training.", "Learn techniques under qualified supervision.", "Use proper body positioning and technique.", "Do not perform dangerous movements.", "Respect training partners and follow the coach's instructions."],
    learningInfo: "Students can learn about stance, movement, takedowns, holds, escapes, control techniques, scoring, rules, and wrestling safety.",
  },
  Gymnastics: {
    name: "Gymnastics",
    emoji: "🤸",
    about: "Gymnastics is a sport involving controlled body movements requiring strength, flexibility, balance, coordination, and body control.",
    origin: "Gymnastics has roots in ancient physical training, particularly in ancient Greece. Modern gymnastics developed through organized physical education systems in Europe and later became an international competitive sport.",
    sportsSpecificOrigin: "Gymnastics has ancient roots, including ancient Greece, while modern competitive gymnastics developed through European physical-education systems. World Gymnastics identifies its ancient roots and later development into modern competitive disciplines.",
    activities: ["Floor exercises", "Balance activities", "Jumps", "Rolls", "Handstands", "Body-control movements"],
    exercises: ["Flexibility exercises", "Core exercises", "Squats", "Strength exercises", "Balance exercises"],
    drills: [
      { name: "Balance Drill", description: "Practice maintaining controlled body position." },
      { name: "Roll Drill", description: "Practice basic rolling movements on a proper mat." },
      { name: "Landing Drill", description: "Practice controlled and safe landing technique." },
    ],
    practiceSuggestions: ["Start with basic movements.", "Use appropriate mats.", "Practice under teacher/coach supervision.", "Focus on control before difficulty."],
    trainingActivities: ["Warm-up", "Flexibility training", "Strength training", "Balance training", "Cool-down"],
    facilities: ["Gymnastics Training Area — provides adequate space for gymnastics activities.", "Floor Exercise Area — used for floor routines and movement skills.", "Vaulting Area — used for vaulting activities.", "Apparatus Area — contains equipment used for different gymnastics events."],
    equipment: ["Gymnastics Mat — provides cushioning during practice.", "Balance Beam — used for balance and movement skills.", "Horizontal Bar — used for swinging and other gymnastics movements.", "Parallel Bars — used for strength, balance, and movement skills.", "Rings — used for strength and body-control exercises.", "Vaulting Equipment — used for vaulting skills."],
    usesFunctions: "Gymnastics equipment supports balance, flexibility, strength, coordination, body control, and skill development.",
    properUseSafety: ["Use mats and equipment properly.", "Check equipment before use.", "Practice under qualified supervision.", "Maintain enough space around apparatus.", "Perform skills according to your ability level.", "Follow proper landing and spotting procedures."],
    learningInfo: "Students can learn about balance, flexibility, body control, rolls, jumps, handstands, landings, basic gymnastics skills, apparatus, terminology, and safety practices.",
  },
};
export const SPORT_CATEGORY: Record<string, string> = {
  Swimming: "Individual Sport",
  Athletics: "Individual Sport",
  Basketball: "Team Sport",
  Badminton: "Racket Sport",
  Chess: "Mind Sport",
  Arnis: "Combat Sport",
  Football: "Team Sport",
  Taekwondo: "Combat Sport",
  Volleyball: "Team Sport",
  "Sepak Takraw": "Team Sport",
  "Wushu Sanda": "Combat Sport",
  Wrestling: "Combat Sport",
  Gymnastics: "Individual Sport",
};
